/**
 * Request/response correlation for orchestrator <-> control/serving round
 * trips (spec-06 §1).
 *
 * The pending resolver for an outbound request is keyed by `jobId` — a
 * globally-unique id generated by the backend for each HTTP request — rather
 * than by `projectId`. That way two concurrent build/prompt/run operations for
 * the same project each register their own resolver and each resolve with
 * their own matching response instead of overwriting one another.
 *
 * Fall back to `projectId` as the key only for callers that never had a jobId.
 */
export function idKey(projectId: string, jobId?: string): string {
    return jobId && jobId.length > 0 ? jobId : projectId;
}

/**
 * A single-slot waiter registry per correlation key. Exactly one resolver may
 * be pending per key (mirroring the orchestrator's per-request model after the
 * spec-06 §1 fix), with an automatic timeout that clears the slot.
 */
export class CorrelationResolver<T> {
    private waiters = new Map<string, (value: T) => void>();

    wait(key: string, timeoutMs: number, label: string): Promise<T> {
        return new Promise<T>((resolve, reject) => {
            const timer = setTimeout(() => {
                this.waiters.delete(key);
                reject(new Error(`${label} timeout for ${key}`));
            }, timeoutMs);

            this.waiters.set(key, (value) => {
                clearTimeout(timer);
                resolve(value);
            });
        });
    }

    /**
     * Resolves the pending waiter for `key` (if any) with `value`. Returns
     * true when a waiter was resolved, false when there was nobody waiting
     * (a late reply after the HTTP caller already timed out).
     */
    resolve(key: string, value: T): boolean {
        if (!this.waiters.has(key)) {
            return false;
        }
        const resolve = this.waiters.get(key)!;
        this.waiters.delete(key);
        resolve(value);
        return true;
    }
}
